# builds the react app copies build dir to gh-pages branch
# do not need the gh-pages npm pkg, this script achieves that purpose
name: folio to GH Pages deploy

on:
  push:
    branches: master

  pull_request:
    branches: master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ENDPOINT: ${{ secrets.REACT_APP_API_ENDPOINT }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '^18.20.2'

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build
        run: |
          cd client
          npm run build

      - name: Deploy to GH Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/build
